name       : viewnior
version    : '1.8'
release    : 8
source     :
    - https://github.com/hellosiyan/Viewnior/archive/refs/tags/viewnior-1.8.tar.gz : b9319171ebca23929e6ea8039c194b1595d92e764db5e3890836fb5c36e233b0
homepage   : https://siyanpanayotov.com/project/viewnior
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fast and elegant image viewer
description: |
    Viewnior, an image viewer program. Created to be simple, fast and elegant. It's minimalistic interface provides more screenspace for your images.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libssh)
    - pkgconfig(shared-mime-info)
    - gnome-common
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
