name       : viewnior
version    : 1.6
release    : 4
source     :
    - https://github.com/xsisqox/Viewnior/archive/viewnior-1.6.tar.gz : 89013f6d30c1c121d8cb6327d3ffc35a757fba1d777c24849d632afe244e60a0
license    : GPL-3.0
summary    : Fast and elegant image viewer
clang      : no
description: |
    Viewnior, an image viewer program. Created to be simple, fast and elegant. It's minimalistic interface provides more screenspace for your images.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(exiv2)
    - pkgconfig(shared-mime-info)
    - gnome-common
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
