name       : viewnior
version    : '1.7'
release    : 7
source     :
    - https://github.com/hellosiyan/Viewnior/archive/viewnior-1.7.tar.gz : b9fad3b2909a78f65b33f4dfb47fcdfa97150275e00d5c44d0aa0f1dc499f3e6
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fast and elegant image viewer
description: |
    Viewnior, an image viewer program. Created to be simple, fast and elegant. It's minimalistic interface provides more screenspace for your images.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(exiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
    - pkgconfig(shared-mime-info)
    - gnome-common
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
